### ISSUE TITLE
Blog Post Review - Team: BananaHammocks

### ISSUE THREAD

**Issue by FarkIst** [rasmus-bn/Investigation-Reporting-Blog#1]
| Technical Dimensions / Weight                                | Does Not Meet Expectations (1-3 points)                                                         | Meets Expectations (4-7 points)                                                                             | Exceeds Expectations (8-10 points)                                                                                                          | Score |
|--------------------------------------------------------------|-------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------|-------|
| **Overview 30%**                                             | Fails to provide an overview and define the scope of the work                                   | Provides an adequate overview and general explanation on the scope of the work                              | Provides a thorough overview and thoroughly defines the scope of the work                                                                   |    9   |
| **Reliable Data from Credible Sources 10%**                  | Data not reliable and fails to provide reference to source of data                              | Adequately describes selection of data and provides a general explanation on source of data                 | Provides in-depth explanations on data selection and credible sources with clear and complete references                                    |   8   |
| **Design Constraints and Assumptions 15%**                   | Fails to discuss design constraints and alternatives; provides no justification for assumptions | Adequately explains and justifies the design constraints, design alternatives and assumptions used          | In-depth explanations and justifications are provided on design constraints, alternatives and assumptions used                              |   7    |
| **Theoretical Explanations 20%**                             | Fails to adequately cover theoretical explanations                                              | Adequately addresses theoretical explanations                                                               | Demonstrates in-depth research and analysis                                                                                                 |    5   |
| **Design Criteria, Sample Calculations and Simulations 20%** | Fails to provide appropriate design methodology, relevant sample calculations, and simulations  | Demonstrates adequate level of design criteria and relevant sample calculations and appropriate simulations | Provides in-depth explanations on design criteria, thoroughly discusses all required calculation steps and uses simulations where necessary |    8  |
| **Previous Work / Future Work 5%**                           | Fails to summarize previous work or to discuss future work                                      | Adequately summarizes previous work and discusses potential future work                                     | Provides a thorough summary of previous workand proposes and discusses future work in detail                                                |    9   |
| **Total 100%**                                               |                      76.66  %                                                                         | **Technical / Content Criteria**                                                                            |                                                                                                                                             |    46   |

You have a nicely formulated blog post in general, however there are small suggestions that I might want to add:

* I can not see the members of the team, not that that is very important in a blog post, but I think it should be there.
* I see that you do have references, but I would like to see them not embedded, but as a section in the blog.
* I think that the conclusion is nicely formulated, includes your subjective view. However, I think it would be great if you could make a summary in this area, with examples or cases where each of these techniques presented are useful.

**Comment by rasmus-bn** [comment]
Added team member name.
Added references in the end.
Conclusion reworked
