### ISSUE TITLE
review

### ISSUE THREAD

**Issue by DavidCarl** [rasmus-bn/Investigation-Reporting-Blog#2]
| Technical Dimensions / Weight                                | Does Not Meet Expectations (1-3 points)                                                         | Meets Expectations (4-7 points)                                                                             | Exceeds Expectations (8-10 points)                                                                                                          | Score |
|--------------------------------------------------------------|-------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------|-------|
| **Overview 30%**                                             | Fails to provide an overview and define the scope of the work                                   | Provides an adequate overview and general explanation on the scope of the work                              | Provides a thorough overview and thoroughly defines the scope of the work                                                                   |    7   |
| **Reliable Data from Credible Sources 10%**                  | Data not reliable and fails to provide reference to source of data                              | Adequately describes selection of data and provides a general explanation on source of data                 | Provides in-depth explanations on data selection and credible sources with clear and complete references                                    |    9   |
| **Design Constraints and Assumptions 15%**                   | Fails to discuss design constraints and alternatives; provides no justification for assumptions | Adequately explains and justifies the design constraints, design alternatives and assumptions used          | In-depth explanations and justifications are provided on design constraints, alternatives and assumptions used                              |    6   |
| **Theoretical Explanations 20%**                             | Fails to adequately cover theoretical explanations                                              | Adequately addresses theoretical explanations                                                               | Demonstrates in-depth research and analysis                                                                                                 |    6   |
| **Design Criteria, Sample Calculations and Simulations 20%** | Fails to provide appropriate design methodology, relevant sample calculations, and simulations  | Demonstrates adequate level of design criteria and relevant sample calculations and appropriate simulations | Provides in-depth explanations on design criteria, thoroughly discusses all required calculation steps and uses simulations where necessary |    5   |
| **Previous Work / Future Work 5%**                           | Fails to summarize previous work or to discuss future work                                      | Adequately summarizes previous work and discusses potential future work                                     | Provides a thorough summary of previous workand proposes and discusses future work in detail                                                |   7   |
| **Total 100%**                                               |            64.5%                                                                                     | **Technical / Content Criteria**                                                                            |                                                                                                                                             |   40    |
 - We feel the quality of the written text is very good, but we also feel like its a hard subject to fulfill all the requirements on the 8 - 10 points scale.
 - We would have like to see some references to futher reading matial as some of the is only explained very shortly (due to length restrictions), and some to back the experiment and conclusions.
 - As we read it we didnt really find a design criteria, is it just us with no AI experience reading it wrong? Unless the it must be numbers is design criteria.
 - We were big fans of the 'technical details' section. Gave us a better background explanation.

 Sincerly

 @davidcarl && @Alfen321

**Comment by rasmus-bn** [comment]
I have added more explanatory references.
The design criteria and the technical part should be more clear now
